"""
Smart Expense Tracker API.

Endpoints:
  POST   /expenses                  -> add an expense
  GET    /expenses                  -> list expenses (optional ?category=)
  GET    /expenses/total            -> overall total + breakdown by category
  GET    /expenses/summary/monthly  -> totals grouped by YYYY-MM (bonus)
  DELETE /expenses/{expense_id}     -> delete an expense by id

Interactive docs are auto-generated by FastAPI at /docs (Swagger UI)
and /redoc.
"""
from collections import defaultdict
from typing import Optional

from fastapi import FastAPI, HTTPException, Query

from .models import CategoryTotal, Expense, ExpenseCreate, TotalsResponse
from .storage import ExpenseStore

app = FastAPI(
    title="Smart Expense Tracker API",
    description="A small REST API for tracking personal expenses.",
    version="1.0.0",
)

store = ExpenseStore()


@app.post("/expenses", response_model=Expense, status_code=201)
def add_expense(payload: ExpenseCreate) -> Expense:
    """Add a new expense. The id is generated by the server."""
    return store.add(payload)


@app.get("/expenses", response_model=list[Expense])
def list_expenses(
    category: Optional[str] = Query(
        None, description="Filter results to a single category (case-insensitive)"
    )
) -> list[Expense]:
    """List all expenses, optionally filtered by category."""
    return store.list_all(category=category)


@app.get("/expenses/total", response_model=TotalsResponse)
def get_totals(
    category: Optional[str] = Query(
        None, description="If set, overall_total reflects only this category"
    )
) -> TotalsResponse:
    """
    Return the overall total and a breakdown by category.
    If `category` is given, `overall_total` is scoped to that category
    (by_category still shows the full breakdown for context).
    """
    all_expenses = store.list_all()

    by_category: dict[str, float] = defaultdict(float)
    for e in all_expenses:
        by_category[e.category] += e.amount

    if category is not None:
        scoped = store.list_all(category=category)
        overall_total = round(sum(e.amount for e in scoped), 2)
    else:
        overall_total = round(sum(e.amount for e in all_expenses), 2)

    return TotalsResponse(
        overall_total=overall_total,
        by_category=[
            CategoryTotal(category=cat, total=round(total, 2))
            for cat, total in sorted(by_category.items())
        ],
    )


@app.get("/expenses/summary/monthly")
def monthly_summary() -> dict[str, float]:
    """Bonus endpoint: totals grouped by month, e.g. {'2026-07': 1234.5}."""
    totals: dict[str, float] = defaultdict(float)
    for e in store.list_all():
        key = e.date.strftime("%Y-%m")
        totals[key] += e.amount
    return {month: round(total, 2) for month, total in sorted(totals.items())}


@app.delete("/expenses/{expense_id}", status_code=204)
def delete_expense(expense_id: int) -> None:
    """Delete an expense by id. Returns 404 if it doesn't exist."""
    deleted = store.delete(expense_id)
    if not deleted:
        raise HTTPException(status_code=404, detail=f"Expense {expense_id} not found")
